<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>ÉLAN — Travel beyond</title>
<meta name="description" content="Private journeys designed around the way you want to feel.">
<meta name="theme-color" content="#0c0d0e">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Playfair+Display:wght@500;600&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{{ asset('css/site.css') }}?v=20260930">
</head>
<body>
<div class="loader" id="loader"><div class="loader-top"><span>ÉLAN</span><span>Private travel studio</span></div><div class="loader-count"><strong id="loaderCount">00</strong><span>%</span></div><div class="loader-line"><i id="loaderLine"></i></div></div>
<div class="noise"></div><div class="cursor" id="cursor"><span class="cursor-core"></span><span class="cursor-label">VIEW</span></div>
<header class="site-header" id="header"><a href="#top" class="brand magnetic">ÉLAN<small>Travel beyond</small></a><nav><a href="#journeys" data-cursor="VIEW">Journeys</a><a href="#philosophy" data-cursor="VIEW">Philosophy</a><a href="#journal" data-cursor="VIEW">Journal</a></nav><a class="header-cta magnetic" href="#booking">Start a journey <span>↗</span></a><button class="menu" id="menuBtn"><i></i><i></i></button></header>
<main id="top">
<section class="hero" data-scene>
  <div class="hero-bg" data-parallax=".09"></div><div class="hero-glow"></div><div class="hero-grid"></div>
  <div class="hero-content"><div class="hero-kicker clip-reveal"><span>CURATED ESCAPES / 2026</span><span>01</span></div><h1 class="hero-title"><span>Go</span><span>somewhere</span><span>extraordinary.</span></h1><div class="hero-bottom"><p class="hero-description fade-up">Private journeys through landscapes that change the way a place stays with you.</p><a href="#journeys" class="circle-cta magnetic" data-cursor="EXPLORE"><span>Explore</span><b>↘</b></a></div></div>
  <div class="hero-scroll"><span>Scroll to wander</span><i></i></div>
</section>
<section class="statement section" id="philosophy"><div class="section-meta fade-up"><span>01 / Philosophy</span><span>Designed around you</span></div><div class="statement-grid"><h2 class="serif reveal-lines">Travel should feel<br><em>like a story.</em></h2><div class="statement-side fade-up"><p>Not a package. Not a checklist. A considered sequence of landscapes, stays and moments shaped around how you want to move through the world.</p><div class="stat-row"><div><strong>18</strong><span>regions</span></div><div><strong>42</strong><span>private routes</span></div><div><strong>97%</strong><span>return guests</span></div></div></div></div><div class="marquee"><div>GO SLOW&nbsp;&nbsp; / &nbsp;&nbsp;LOOK CLOSER&nbsp;&nbsp; / &nbsp;&nbsp;LEAVE ROOM FOR THE UNEXPECTED&nbsp;&nbsp; / &nbsp;&nbsp;</div><div>GO SLOW&nbsp;&nbsp; / &nbsp;&nbsp;LOOK CLOSER&nbsp;&nbsp; / &nbsp;&nbsp;LEAVE ROOM FOR THE UNEXPECTED&nbsp;&nbsp; / &nbsp;&nbsp;</div></div></section>
<section class="journeys" id="journeys"><div class="section-head section"><div><div class="section-meta fade-up"><span>02 / Signature journeys</span><span>Swipe / drag</span></div><h2 class="serif reveal-lines">Places with a pulse.</h2></div><p class="fade-up">Handpicked routes for people who would rather feel the destination than tick it off.</p></div><div class="journey-viewport"><div class="journey-track" id="journeyTrack"><div class="journey-loading">Loading journeys…</div></div></div><div class="journey-controls section"><div class="progress"><i id="journeyProgress"></i></div><div class="controls-right"><span id="journeyIndex">01 / —</span><button id="journeyPrev">←</button><button id="journeyNext">→</button></div></div></section>
<section class="cinema" data-scene><div class="cinema-bg" data-parallax=".12"></div><div class="cinema-shade"></div><div class="cinema-inner section"><div class="section-meta"><span>03 / The ÉLAN way</span><span>Made to linger</span></div><div class="cinema-quote reveal-lines">“The destination<br>is only <em>half<br>the journey.</em>”</div><div class="cinema-bottom fade-up"><span>Designed around you.</span><p>Every itinerary is composed from scratch, with private guides, characterful stays and enough negative space for the unexpected to become part of the story.</p></div></div></section>
<section class="journal section" id="journal"><div class="section-meta fade-up"><span>04 / Journal</span><span>Field notes</span></div><div id="journalList"><div class="journal-loading">Loading field notes…</div></div></section>
<section class="booking section" id="booking"><div class="booking-shell"><div class="booking-copy"><div class="section-meta"><span>05 / Start a journey</span><span>Private enquiries</span></div><h2 class="serif reveal-lines">Tell us where<br><em>you want to feel.</em></h2><p class="fade-up">A first conversation is enough. Tell us what you are drawn to, and we’ll shape the route from there.</p></div><form id="bookingForm" class="booking-form"><div class="field"><label>Your name</label><input name="name" required placeholder="Full name"></div><div class="field"><label>Email</label><input name="email" type="email" required placeholder="you@example.com"></div><div class="field"><label>Destination / idea</label><input name="destination" placeholder="Iceland, Kyoto, desert…"></div><div class="field split"><div><label>Travel date</label><input name="travel_date" type="date"></div><div><label>Guests</label><input name="guests" type="number" min="1" max="20" value="2"></div></div><button class="submit magnetic" data-cursor="SEND">Begin the conversation <span>↗</span></button><p class="form-status" id="formStatus"></p></form></div></section>
</main>
<footer class="footer section"><div class="footer-brand">ÉLAN<small>Travel beyond</small></div><div>© 2026 ÉLAN Travel Studio</div><a href="/admin">Studio access ↗</a></footer>
<svg class="svg-filters" aria-hidden="true"><defs><filter id="liquid"><feTurbulence type="fractalNoise" baseFrequency="0.015 0.035" numOctaves="2" seed="4" result="noise"/><feDisplacementMap in="SourceGraphic" in2="noise" scale="0" xChannelSelector="R" yChannelSelector="B"/></filter></defs></svg>
<script src="https://cdn.jsdelivr.net/npm/gsap@3/dist/gsap.min.js"></script><script src="https://cdn.jsdelivr.net/npm/gsap@3/dist/ScrollTrigger.min.js"></script><script src="https://cdn.jsdelivr.net/npm/lenis@latest/dist/lenis.min.js"></script>
<script src="{{ asset('js/site.js') }}?v=20260930"></script>
</body></html>